<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/fonts/font-awesome-4.7.0/css/font-awesome.css">
<link href="/css/dashboard.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="/css/side.css">
<link rel="icon" type="image/png" href="/images/icons/favicon.ico"/>
