<!-- Sidebar (hidden by default) -->
<nav class="w3-sidebar w3-bar-block w3-card w3-top w3-xlarge w3-animate-left" style="display:none;z-index:2;width:40%;min-width:300px" id="mySidebar">

    <a href="javascript:void(0)" onclick="w3_close()" class="w3-bar-item w3-button"><@spring.message "books.sidebar.close"/></a>

    <a href="<@spring.message "books.sidebar.books.link"/>" onclick="w3_close()" class="w3-bar-item w3-button"><@spring.message "books.sidebar.books"/></a>
    <a href="<@spring.message "books.sidebar.about.link"/>" onclick="w3_close()" class="w3-bar-item w3-button"><@spring.message "books.sidebar.about"/></a>
</nav>
