<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Project Future Team 0</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css'>
    <link rel="stylesheet" href="assets/style.css">
</head>

<body>
<head>
    <link rel="shortcut icon" type="image/x-icon" href="https://image.ibb.co/n5gUtm/icon_1.png"/>
    <meta name="theme-color" content="#daa37f">
    <title>Under Construction - Homepage</title>
</head>

<body>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
<link href="https://fonts.googleapis.com/css?family=Merriweather:400,900,900i" rel="stylesheet">
<a id="button"></a>
<div class="banner">
    <div class="banner__overlay">
        <div class="banner__container">
            <h1 class="banner__title">Your help is Here</h1>
            <p class="banner__text">Helping you till 2019</p>
            <a href="login" class="btn btn--opacity">Log In</a>
        </div>
        <img class="banner__scroll-down" src="data:image/svg+xml;utf8;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4KPHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB2ZXJzaW9uPSIxLjEiIHZpZXdCb3g9IjAgMCAxMjkgMTI5IiBlbmFibGUtYmFja2dyb3VuZD0ibmV3IDAgMCAxMjkgMTI5IiB3aWR0aD0iMjRweCIgaGVpZ2h0PSIyNHB4Ij4KICA8Zz4KICAgIDxwYXRoIGQ9Im0xMjEuMywzNC42Yy0xLjYtMS42LTQuMi0xLjYtNS44LDBsLTUxLDUxLjEtNTEuMS01MS4xYy0xLjYtMS42LTQuMi0xLjYtNS44LDAtMS42LDEuNi0xLjYsNC4yIDAsNS44bDUzLjksNTMuOWMwLjgsMC44IDEuOCwxLjIgMi45LDEuMiAxLDAgMi4xLTAuNCAyLjktMS4ybDUzLjktNTMuOWMxLjctMS42IDEuNy00LjIgMC4xLTUuOHoiIGZpbGw9IiNGRkZGRkYiLz4KICA8L2c+Cjwvc3ZnPgo=" />
    </div>
</div>
<div class="sect sect--type">
    <div class="container">
        <div class="row row--center">
            <div class="col-md-5 col-xs-8 col-sm-6 col--inbl">
                <h1 class="sect__title">We believe in the perfect result</h1>
                <p class="sect__subtitle">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
            </div>
        </div>
        <div class="row row--small row--margin row--center">
            <div class="col-md-4 col-sm-4 repair">
                <img src="https://cdn4.iconfinder.com/data/icons/ios-edge-glyph-8/25/Plumbing-512.png" class="repair__img">
                <h2 class="repair__name">Plumbing</h2>
                <p class="repair__descr">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
            </div>

            <div class="col-md-4 col-sm-4 repair">
                <img src="https://cdn0.iconfinder.com/data/icons/real-estate-2-26/66/74-512.png" class="repair__img">
                <h2 class="repair__name">Electricity</h2>
                <p class="repair__descr">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
            </div>

            <div class="col-md-4 col-sm-4 repair">
                <img src="https://png2.cleanpng.com/sh/4438730551018239fd538ac3df921af7/L0KzQYm3VsA5N6p9jpH0aYP2gLBuTgBqa6V0fARqbT3qdbL5TgN6dZN0hJ8AYkHlRIXrUPVlPZVpUJCDMkW4QYa4VcE2Omk6SaUCNES8R4O6TwBvbz==/kisspng-pictogram-gear-symbol-5b1b44d0ed5dd8.8255151515285137449723.png" class="repair__img">
                <h2 class="repair__name">Insulation</h2>
                <p class="repair__descr">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
            </div>
        </div>
    </div>
</div>


<!-- <div class="container">
    <div class="row row--center">
      <div class="col-md-5 col-sm-6 col--inbl">
        <h1 class="sect__title sect--white-text">Our Beggining</h1>
        <p class="sect__subtitle sect--white-text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
      </div>
    </div>
  </div>

-->

<div class="bg-img"></div>

<div class="half-sect">
    <div class="half half-sect__first">
        <div class="description">
            <h2 class="description__title">New Technology</h2>
            <p class="description__p">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
        </div>
    </div>
    <div class="half half-sect__second">  </div>
</div>

<div class="sect sect--great">
    <div class="container">
        <div class="row">
            <div class="col-md-5 col-sm-7 col-sm-offset-4 col-md-offset-6">
                <div class="description">
                    <h2 class="description__title">Great 0ut-come</h2>
                    <p class="description__p">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="sect sect--best sect--center">
    <div class="container">
        <div class="row row--center">
            <div class="col-md-6 col-sm-7 col-xs-12">
                <h1 class="sect__title best--bottom sect--white-text">The "bestest" team</h1>
                <div class="row">
                    <div class="col-md-4 col-sm-4 col-xs-4">
                        <img src="https://cdn3.iconfinder.com/data/icons/user-interface-47/100/Web_development-512.png" class="best__img">
                        <h2 class="best__title">Best plumbers</h2>
                    </div>
                    <div class="col-md-4 col-sm-4 col-xs-4">
                        <img src="https://cdn3.iconfinder.com/data/icons/user-interface-47/100/Web_development-512.png" class="best__img">
                        <h2 class="best__title">Best electricians</h2>
                    </div>
                    <div class="col-md-4 col-sm-4 col-xs-4">
                        <img src="https://cdn3.iconfinder.com/data/icons/user-interface-47/100/Web_development-512.png" class="best__img">
                        <h2 class="best__title">Best performance</h2>
                    </div>
                </div>

                <p class="sect__subtitle best--margin sect--white-text ">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
            </div>
        </div>
    </div>
</div>

<div class="three-img">
    <div class="col-md-4 col-sm-4 col-xs-4 three-img__img three-img--1"></div>
    <div class="col-md-4 col-xs-4 col-sm-4 three-img__img three-img--2"></div>
    <div class="col-md-4 col-xs-4 col-sm-4 three-img__img three-img--3"></div>
</div>


<div class="sect blog sect--grey">
    <div class="container">
        <div class="row row--center">
            <div class="col-md-5 col-sm-6 col--inbl">
                <h1 class="sect__title">Our super-blog</h1>
                <p class="sect__subtitle">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
            </div>
        </div>
        <div class="row last-articles">
            <div class="col-md-4 col-sm-4">
                <div class="article-pre article-pre-1">
                    <div class="article-pre__img">
                    </div>
                    <div class="article-pre__info">
                        <h1 class="article-pre__title">The best plumbers</h1>
                        <span class="article-pre__date">Dec 19, 2019</span>
                        <p class="article-pre__ex">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                    </div>
                </div>
            </div>

            <div class="col-md-4 col-sm-4">
                <div class="article-pre article-pre-2">
                    <div class="article-pre__img">
                    </div>
                    <div class="article-pre__info">
                        <h1 class="article-pre__title">The best way of electricians</h1>
                        <span class="article-pre__date">Dec 20, 2019</span>
                        <p class="article-pre__ex">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                    </div>
                </div>
            </div>

            <div class="col-md-4 col-sm-4">
                <div class="article-pre article-pre-3">
                    <div class="article-pre__img">
                    </div>
                    <div class="article-pre__info">
                        <h1 class="article-pre__title">Why to choose Team 0</h1>
                        <span class="article-pre__date">Dec 21, 2019</span>
                        <p class="article-pre__ex">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="sect-t-footer"></div>

<footer class="footer">
    <div class="footer__half footer__half-1">
        <h2 class="footer__big-title">COME ON IN!</h2>
        <h3 class="footer__title">Weekdays</h3>
        <p class="footer__desc">08:00-17:00</p>
        <h3 class="footer__title">Weekends</h3>
        <p class="footer__desc">10:00 - 13:00</p>
    </div>
    <div class="footer__half footer__half-2">
        <h2 class="footer__big-title">CONTACT</h2>
        <h3 class="footer__title">Phone</h3>
        <p class="footer__desc">1234567890</p>
        <h3 class="footer__title">Mail</h3>
        <p class="footer__desc">team0@hotmail.com</p>
        <h3 class="footer__title">Address</h3>
        <p class="footer__desc">Nea Erithrea<br>GR, Athens</p>
    </div>
</footer>
</body>

<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js'></script>
<script src="assets/script.js"></script>

</body>
</html>